-- $Id: SAMPLE.sql,v 1.1.1.1 2006/01/29 13:03:22 gon Exp $
ALTER TABLE EX_CUSTOMER DROP CONSTRAINT EX_CUSTOMER_DEPARTMENT_FK;
ALTER TABLE EX_CUSTOMER DROP CONSTRAINT EX_CUSTOMER_COMPANY_FK;
ALTER TABLE EX_DEPARTMENT DROP CONSTRAINT EX_DEPARTMENT_COMPANY_FK;

DROP INDEX UNIQ_COMPANY;
DROP INDEX UNIQ_DEPARTMENT;

DROP SEQUENCE ID_CUSTOMER;
DROP SEQUENCE ID_DEPARTMENT;
DROP SEQUENCE ID_COMPANY;

DROP TABLE EX_CUSTOMER;
DROP TABLE EX_DEPARTMENT;
DROP TABLE EX_COMPANY;

CREATE TABLE EX_CUSTOMER (
    ID		          INTEGER		    PRIMARY KEY,
    NAME_FIRSTNAME	VARCHAR(20)		NOT NULL,
    NAME_LASTNAME	  VARCHAR(20)		NOT NULL,
    EMAIL           VARCHAR(100),	
    PHONE           VARCHAR(20),		
    FAX             VARCHAR(20),		
    DEPARTMENT_ID	  INTEGER		    NOT NULL,
    COMPANY_ID	    INTEGER		    NOT NULL
);

--
-- EX_DEPARTMENT
--
CREATE TABLE EX_DEPARTMENT (
    ID		      INTEGER		    PRIMARY KEY,
    NAME		    VARCHAR(100)	NOT NULL,
    ADDRESS     VARCHAR(200),	
    COMPANY_ID	INTEGER		    NOT NULL
);

--
-- EX_COMPANY
--
CREATE TABLE EX_COMPANY (
    ID		INTEGER		    PRIMARY KEY,
    NAME	VARCHAR(100)	NOT NULL
);

--
-- CONSTRAINTS
--
ALTER TABLE EX_CUSTOMER ADD CONSTRAINT EX_CUSTOMER_DEPARTMENT_FK
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES EX_DEPARTMENT (ID);

ALTER TABLE EX_CUSTOMER ADD CONSTRAINT EX_CUSTOMER_COMPANY_FK
    FOREIGN KEY (COMPANY_ID) REFERENCES EX_COMPANY (ID);

ALTER TABLE EX_DEPARTMENT ADD CONSTRAINT EX_DEPARTMENT_COMPANY_FK
    FOREIGN KEY (COMPANY_ID) REFERENCES EX_COMPANY (ID);

--
-- INDEXES
--
CREATE UNIQUE INDEX UNIQ_COMPANY ON EX_COMPANY(NAME);
CREATE UNIQUE INDEX UNIQ_DEPARTMENT ON EX_DEPARTMENT(NAME, COMPANY_ID);

--
-- SEQUENCE
CREATE SEQUENCE ID_CUSTOMER START WITH 4000;
CREATE SEQUENCE ID_DEPARTMENT START WITH 3000;
CREATE SEQUENCE ID_COMPANY START WITH 2000;
